### ISSUE TITLE
wetekplay build fails in enigma2 dvb section on missing include file

### ISSUE THREAD

**Issue by wwortel** [oe-alliance/build-enviroment#10]
see attached snippet from the compile log.
The enigma2 .bb file does give C compile directives for libamcodec. But somehow the missing codec.h header file does not get added to the proper includes staging directory.

Of course have tried to cure this but i am to new to this build environment to fully understand what is done where.
I do find codec.h here:
./builds/openatv/release/wetekplay/tmp/sysroots/wetekplay/usr/include/amlogic/amcodec/codec.h
It gets included from amldecoder.h with these lines:

// Amlogic includes
extern "C" {
# include <codec.h>

}

I assume codec.h should have been added at the /usr/include/ level or the include command must be altered to fetch the codec.h from the /usr/include/amlogic/amcodec/

[codec.h_missing.txt](https://github.com/oe-alliance/build-enviroment/files/363741/codec.h_missing.txt)

**Comment by atvcaptain** [comment]
all ready fixed
