### ISSUE TITLE
build failure while compiling subversion-native-1.9.4

### ISSUE THREAD

**Issue by cYrAx157** [oe-alliance/build-enviroment#11]
ERROR: subversion-native-1.9.4-r0 do_compile: oe_runmake failed
ERROR: subversion-native-1.9.4-r0 do_compile: Function failed: do_compile (log file is located at /home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/work/x86_64-linux/subversion-native/1.9.4-r0/temp/log.do_compile.31920)
ERROR: Logfile of failure stored in: /home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/work/x86_64-linux/subversion-native/1.9.4-r0/temp/log.do_compile.31920
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4
| ERROR: oe_runmake failed
| cd subversion/libsvn_subr && /bin/sh /home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/work/x86_64-linux/subversion-native/1.9.4-r0/build/x86_64-linux-libtool --tag=CC --silent --mode=link gcc   -isystem/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/include -P -march=native -O2 -pipe   -pthread -isystem/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/include -P -march=native -O2 -pipe  -L/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/lib -L/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/lib -Wl,-rpath-link,/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/lib -Wl,-rpath-link,/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/lib -Wl,-rpath,/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/lib -Wl,-rpath,/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/lib -Wl,-O1  -L/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/lib -L/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64   -rpath /home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/lib -version-info 0 -Wl,--no-undefined -o libsvn_subr-1.la  adler32.lo atomic.lo auth.lo base64.lo bit_array.lo cache-inprocess.lo cache-membuffer.lo cache-memcache.lo cache.lo cache_config.lo checksum.lo cmdline.lo compat.lo compress.lo config.lo config_auth.lo config_file.lo config_win.lo crypto.lo ctype.lo date.lo debug.lo deprecated.lo dirent_uri.lo dso.lo eol.lo error.lo fnv1a.lo gpg_agent.lo hash.lo io.lo iter.lo lock.lo log.lo macos_keychain.lo magic.lo md5.lo mergeinfo.lo mutex.lo nls.lo object_pool.lo opt.lo packed_data.lo path.lo pool.lo prefix_string.lo prompt.lo properties.lo quoprint.lo root_pools.lo simple_providers.lo skel.lo sorts.lo spillbuf.lo sqlite.lo sqlite3wrapper.lo ssl_client_cert_providers.lo ssl_client_cert_pw_providers.lo ssl_server_trust_providers.lo stream.lo string.lo subst.lo sysinfo.lo target.lo temp_serializer.lo time.lo token.lo types.lo user.lo username_providers.lo utf.lo utf8proc.lo utf_validate.lo utf_width.lo validate.lo version.lo win32_crashrpt.lo win32_crypto.lo win32_xlate.lo x509info.lo x509parse.lo xml.lo -L/home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/sysroots/x86_64-linux/usr/lib -laprutil-1 -lapr-1 -lexpat -lz  -lsqlite3 -lmagic
| .libs/cmdline.o: In function `svn_cmdline_init':
| cmdline.c:(.text+0x423): undefined reference to `atexit'
| collect2: error: ld returned 1 exit status
| ../subversion-1.9.4/build-outputs.mk:485: recipe for target 'subversion/libsvn_subr/libsvn_subr-1.la' failed
| make: *** [subversion/libsvn_subr/libsvn_subr-1.la] Error 1
| WARNING: /home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/work/x86_64-linux/subversion-native/1.9.4-r0/temp/run.do_compile.31920:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /home/cyrax/openatv/4.0/build-enviroment/builds/openatv/release/gb7358/tmp/work/x86_64-linux/subversion-native/1.9.4-r0/temp/log.do_compile.31920)
ERROR: Task (virtual:native:/home/cyrax/openatv/4.0/build-enviroment/openembedded-core/meta/recipes-devtools/subversion/subversion_1.9.4.bb:do_compile) failed with exit code '1'

**Comment by cYrAx157** [comment]
It´s for the 4.0 branch

**Comment by arn354** [comment]
4.0 branch is not yet in production use - any fix pull-request is welcome :)

**Comment by arn354** [comment]
sorry for closing.
Do you get that on a clean build from 0 ?
Builds fine here.

**Comment by cYrAx157** [comment]
thanks arn and sorry, my machine was messed up :-)
I started a clean build and now it builds fine.
and yeah, I know it is not for production, but I like to play with it :-)
nice work, btw 👍
