### ISSUE TITLE
Makefile violates license of original work

### ISSUE THREAD

**Issue by mtdcr** [oe-alliance/build-enviroment#15]
Dear oe-alliance developers,

now that pull request #13 was reverted in #14, I'd like to ask whether the project's opinion about software licenses is that it's acceptable to violate them if somebody else did it earlier.

As the author of the original work, I kindly request you to add back the copyright and license statement as required by the original MIT license.

I guess the MIT license is permissive enough for everybody and the license terms are easy to comply with. As most of you might know, the OpenEmbedded project is using the same license for its metadata.

Best regards,
Andreas

**Comment by andyblac** [comment]
as I stated I created this git via a 'fork from PLi' not your self, I kept all of their licensing, we are only required to keep what the original git from this git was forked from 'at that time', as their makefile had no such license in the file we are not bound to add any such license info now.

also PLi git is under 'GNU GENERAL PUBLIC LICENSE Version 2, June 1991' not MIT

https://github.com/OpenPLi/openpli-oe-core/commit/2d104e7a25f7cde4adecd00c14b77fe8739e951c#diff-9879d6db96fd29134fc802214163b95a

**Comment by atvcaptain** [comment]
we have update licence info , thx for your info: https://github.com/oe-alliance/build-enviroment/blob/4.0/LICENSE

**Comment by mtdcr** [comment]
@atvcaptain: That was a move into the right direction, but not enough, unfortunately.

In the meantime, OpenPLi added back the copyright and licence header in commit https://github.com/OpenPLi/openpli-oe-core/commit/28e700c0120a07d1fc88a4c2d9faf2c4fb694c28. So even @andyblac's unfunded concerns were fully addressed. For that reason I repeat my request to add back the copyright and license header to your Makefile. I can prepare another PR if desired.

Best wishes,
Andreas

**Comment by mtdcr** [comment]
Just another comment about your updated LICENSE file:

Neither you nor OpenPLi had permission to change the license to the GPLv2, and you also missed crediting OpenPLi, although @andyblac identified it as the source of your fork.

You may, however, add the GPLv2 as an **additional** license, provided that you keep the original license text. I guess there's no point in doing so however, since it's not a compiled language.

Best wishes,
Andreas
