### ISSUE TITLE
python pytz error fetching 

### ISSUE THREAD

**Issue by ghost** [oe-alliance/build-enviroment#16]
ERROR: python-pytz-2017.2-r0 do_fetch: Fetcher failure for URL: 'https://files.pythonhosted.org/packages/source/p/pytz/pytz-2017.2.tar.gz'. Unable to fetch URL from any source.
ERROR: python-pytz-2017.2-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/ostende/e2/build-enviroment/builds/openbh/release/vusolo2/tmp/work/mips32el-oe-linux/python-pytz/python-pytz-2017.2-r0/temp/log.do_fetch.17425
ERROR: Task (/home/ostende/e2/build-enviroment/meta-openembedded/meta-python/recipes-devtools/python/python-pytz_2017.2.bb:do_fetch) failed with exit code '1'

**Comment by atvcaptain** [comment]
we use pytz-2016.10.tar.gz not 2017.2 with branch 4.0 and 4.1

**Comment by remytr-org** [comment]
Hello dear captain, formuler f4 turbo devices, powervu channels still work like iptv, please correct it like other devices or how can i fix it,

And the control responds too late, what could be the reason for the irregular operation (the control works very fast with openpli image)

Thank for all works
