### ISSUE TITLE
gcc-cross-initial-mipsel bzw libgcc under debian 8.8 64 bit not builable

### ISSUE THREAD

**Issue by schleichdi2** [oe-alliance/build-enviroment#17]
Hello, I know the nextp3 is no active branch but under debin 8.8 64 bit is gcc cross-initial mipsel or libgcc not buildable attached a log if it is desired

[log.do_compile.3208.zip](https://github.com/oe-alliance/build-enviroment/files/1054357/log.do_compile.3208.zip)

**Comment by atvcaptain** [comment]
not ready yet use current 4.0 or beta 4.1
