### ISSUE TITLE
The following archs are listed more than once: u5

### ISSUE THREAD

**Issue by linuxstv** [oe-alliance/build-enviroment#19]
MACHINE=u5 DISTRO=openatv make image
check internet connection: Online 
     
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Error, the PACKAGE_ARCHS variable contains duplicates. The following archs are listed more than once: u5

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:838: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by atvcaptain** [comment]
use dinobot4k not u5
