### ISSUE TITLE
Some channels still work like iptv..

### ISSUE THREAD

**Issue by remytr-org** [oe-alliance/build-enviroment#20]
Hello dear captain, formuler f4 turbo devices, powervu channels still work like iptv, please correct it like other devices or how can i fix it,

And the control responds too late, what could be the reason for the irregular operation (the control works very fast with openpli image)

Thank for all works

**Comment by atvcaptain** [comment]
i dont unterstand ?

use pli same kernel and driver , i dont know , i dont have pvu i cant test it

**Comment by remytr-org** [comment]
Dear captain,
formuler f1 and other vuplus devices are running powervu channels, drivers of these devices have been updated, no new driver support has been given to the formula f4 turbo device, we do not want to use open pli because i support openatv image ..
Formuler f1 : powervu channels run not need stream..
Formuler f4 turbo: powervu channels run only with stream
🙄

**Comment by atvcaptain** [comment]
i ask driver team

**Comment by atvcaptain** [comment]
formuler stop driver support
