### ISSUE TITLE
OpenATV for Alien5 Compile Error "Function failed: do_rootfs"

### ISSUE THREAD

**Issue by engineerkhan15** [oe-alliance/build-enviroment#22]
I am trying to compile OpenATV Image for Alien5 on Ubuntu 16.04 LTS. 
I encountered this error at 99% progress "Function failed: do_rootfs". Here is the log.
`def do_rootfs(d):
    from oe.rootfs import create_rootfs
    from oe.manifest import create_manifest
    import logging

    logger = d.getVar('BB_TASK_LOGGER', False)
    if logger:
        logcatcher = bb.utils.LogCatcher()
        logger.addHandler(logcatcher)
    else:
        logcatcher = None

    # NOTE: if you add, remove or significantly refactor the stages of this
    # process then you should recalculate the weightings here. This is quite
    # easy to do - just change the MultiStageProgressReporter line temporarily
    # to pass debug=True as the last parameter and you'll get a printout of
    # the weightings as well as a map to the lines where next_stage() was
    # called. Of course this isn't critical, but it helps to keep the progress
    # reporting accurate.
    stage_weights = [1, 203, 354, 186, 65, 4228, 1, 353, 49, 330, 382, 23, 1]
    progress_reporter = bb.progress.MultiStageProgressReporter(d, stage_weights)
    progress_reporter.next_stage()

    # Handle package exclusions
    excl_pkgs = d.getVar("PACKAGE_EXCLUDE").split()
    inst_pkgs = d.getVar("PACKAGE_INSTALL").split()
    inst_attempt_pkgs = d.getVar("PACKAGE_INSTALL_ATTEMPTONLY").split()

    d.setVar('PACKAGE_INSTALL_ORIG', ' '.join(inst_pkgs))
    d.setVar('PACKAGE_INSTALL_ATTEMPTONLY', ' '.join(inst_attempt_pkgs))

    for pkg in excl_pkgs:
        if pkg in inst_pkgs:
            bb.warn("Package %s, set to be excluded, is in %s PACKAGE_INSTALL (%s).  It will be removed from the list." % (pkg, d.getVar('PN'), inst_pkgs))
            inst_pkgs.remove(pkg)

        if pkg in inst_attempt_pkgs:
            bb.warn("Package %s, set to be excluded, is in %s PACKAGE_INSTALL_ATTEMPTONLY (%s).  It will be removed from the list." % (pkg, d.getVar('PN'), inst_pkgs))
            inst_attempt_pkgs.remove(pkg)

    d.setVar("PACKAGE_INSTALL", ' '.join(inst_pkgs))
    d.setVar("PACKAGE_INSTALL_ATTEMPTONLY", ' '.join(inst_attempt_pkgs))

    # Ensure we handle package name remapping
    # We have to delay the runtime_mapping_rename until just before rootfs runs
    # otherwise, the multilib renaming could step in and squash any fixups that
    # may have occurred.
    pn = d.getVar('PN')
    runtime_mapping_rename("PACKAGE_INSTALL", pn, d)
    runtime_mapping_rename("PACKAGE_INSTALL_ATTEMPTONLY", pn, d)
    runtime_mapping_rename("BAD_RECOMMENDATIONS", pn, d)

    # Generate the initial manifest
    create_manifest(d)

    progress_reporter.next_stage()

    # generate rootfs
    create_rootfs(d, progress_reporter=progress_reporter, logcatcher=logcatcher)

    progress_reporter.finish()

do_rootfs(d)

def runtime_mapping_rename (varname, pkg, d):
    #bb.note("%s before: %s" % (varname, d.getVar(varname)))

    new_depends = {}
    deps = bb.utils.explode_dep_versions2(d.getVar(varname) or "")
    for depend in deps:
        new_depend = get_package_mapping(depend, pkg, d)
        new_depends[new_depend] = deps[depend]

    d.setVar(varname, bb.utils.join_deps(new_depends, commasep=False))

    #bb.note("%s after: %s" % (varname, d.getVar(varname)))

def get_package_mapping (pkg, basepkg, d):
    import oe.packagedata

    data = oe.packagedata.read_subpkgdata(pkg, d)
    key = "PKG_%s" % pkg

    if key in data:
        # Have to avoid undoing the write_extra_pkgs(global_variants...)
        if bb.data.inherits_class('allarch', d) and data[key] == basepkg:
            return pkg
        return data[key]

    return pkg`

**Comment by arn354** [comment]
i see no log here - i only see the functions itself.
this box seems to be recently added and is still changed a lot the past days.
You may contribute or wait untill someone else has successfully build.

**Comment by engineerkhan15** [comment]
Sorry, I pasted contents of wrong file. Here is the error message from log file:

> ERROR: Index creation command '/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/work/alien5-oe-linux/openatv-image/6.1-0/recipe-sysroot-native/usr/bin/opkg-make-index -r /home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/deploy/ipk/3rdparty/Packages -p /home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/deploy/ipk/3rdparty/Packages -m /home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/deploy/ipk/3rdparty' failed with return code 1:
> Traceback (most recent call last):
>   File "/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/work/alien5-oe-linux/openatv-image/6.1-0/recipe-sysroot-native/usr/bin/opkg-make-index", line 125, in <module>
>     pkg = opkg.Package(abspath, relpath=pkg_dir)
>   File "/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/work/alien5-oe-linux/openatv-image/6.1-0/recipe-sysroot-native/usr/bin/opkg.py", line 167, in __init__
>     ar = arfile.ArFile(f, fn)
>   File "/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/work/alien5-oe-linux/openatv-image/6.1-0/recipe-sysroot-native/usr/bin/arfile.py", line 54, in __init__
>     assert signature == "!<arch>\n" or signature == b"!<arch>\n", "Old ipk format (non-deb) is unsupported, file: %s, magic: %s, expected %s" % (fn, signature, "!<arch>")
> AssertionError: Old ipk format (non-deb) is unsupported, file: /home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/alien5/tmp/deploy/ipk/3rdparty/enigma2-plugin-extensions-mediaportal_all.ipk, magic: 
> , expected !<arch>
> 
> DEBUG: Python function do_rootfs finished
> ERROR: Function failed: do_rootfs

Looking into this message, I found that the error is related with a 3rd party plugin "mediaportal". I omitted that plugin from the recipe and then the Image was compiled successfully.

**Comment by atvcaptain** [comment]
wget --unlink  http://master.dl.sourceforge.net/project/e2-mediaportal/enigma2-plugin-extensions-mediaportal_all.ipk
--2018-05-17 17:00:22--  http://master.dl.sourceforge.net/project/e2-mediaportal/enigma2-plugin-extensions-mediaportal_all.ipk
Resolving master.dl.sourceforge.net (master.dl.sourceforge.net)... 216.105.38.12
Connecting to master.dl.sourceforge.net (master.dl.sourceforge.net)|216.105.38.12|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3342688 (3.2M) [application/octet-stream]
Saving to: ‘enigma2-plugin-extensions-mediaportal_all.ipk.1’

enigma2-plugin-extensions-mediaportal_all.ipk 100%[==============================================================================================>]   3.19M  2.95MB/s    in 1.1s

2018-05-17 17:00:23 (2.95 MB/s) - ‘enigma2-plugin-extensions-mediaportal_all.ipk.1’ saved [3342688/3342688]


download works here no issue
