### ISSUE TITLE
Cloning the files

### ISSUE THREAD

**Issue by UoPTucson** [oe-alliance/build-enviroment#23]
In your instructions for 'git'ing the files you state:
git clone git://github.com/oe-alliance/build-enviroment.git -b 4.1

When I try to do this I get:
Cloning into 'build-enviroment'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Connection timed out

2 issues:
1) You need to pull from https:  not git:
2) Do you need to change the make update instructions?

Thank you for your time.
Randy

**Comment by arn354** [comment]
```
root@teamblue:/tmp# git clone git://github.com/oe-alliance/build-enviroment.git -b 4.2
Cloning into 'build-enviroment'...
remote: Counting objects: 20192, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 20192 (delta 12), reused 21 (delta 7), pack-reused 20166
Receiving objects: 100% (20192/20192), 15.72 MiB | 11.46 MiB/s, done.
Resolving deltas: 100% (10474/10474), done.
Checking connectivity... done.
root@teamblue:/tmp#
```

Works here as expected - i do not see the command you initially used - maybe a typo... - or sometimes github is just not responding.

-b is the used branch you want to clone
e.g. 4.1 = openatv 6.1
e.g. 4.2 = openatv 6.2
...
