### ISSUE TITLE
allow enigma2 to be built in 32 mode under multilib support

### ISSUE THREAD

**Issue by moham96** [oe-alliance/build-enviroment#25]
Hi, 
I'm developing enigma2 for amlogic devices(specifically the mecool devices k2pro k1pro k3pro k1plus), These devices are very similar to Amiko Alien5(which oealliance already has a meta layer for), I got the dvb tuner partially working (enigma2 can scan channels but have a problem with the demuxer), unfortunately, the tuner board on these devices (avl6862 demod and r848a tuner) require that the userspace that calls them to be compiled in 32bit mode (armv7), up untill now I've been using the rootfs of wetekplay( because it's 32bit) and a compiled kernel from coreelec for my device but to investigate this demuxer problem further I need to compile enigma2 in 32 bit myself which I like to do using the alien5 machine conf for now, the alien5 already has multilib enabled so the 32 libraries are built into the image, all I need is to force enigma to be compiled in 32bit mode which should be something like
`MACHINE=alien5 bitbake lib32-enigma2`
but unfortunately, enigma2 fails to build due to missing dependencies 

> ERROR: Nothing RPROVIDES 'lib32-gstreamer1.0-plugins-ugly-asf' (but virtual:multilib:lib32:/home/oealliancebuilder/oealliance/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb RDEPENDS on or otherwise requires it)

and even if I remove the gstreamer1.0-plugins-ugly-asf from the dependencies I get more errors.
I think that this is a problem with only enigma2 recipe since other programs compile fine in 32 bit mode  and only enigma2 fails to compile.
Does someone have an insight into this and how it can be solved?
Thanks

**Comment by atvcaptain** [comment]
with alien5 no issue please check again

**Comment by moham96** [comment]
@atvcaptain Did you build enigma2 in 32bit mode? cause I still get errors
```
mohammad@mohammad-pc:~/repos/build-enviroment/builds/openatv/release/alien5$ bitbake lib32-enigma2
Loading cache: 100% |############################################################################################################| Time: 0:00:03
Loaded 7603 entries from dependency cache.
Parsing recipes: 100% |##########################################################################################################| Time: 0:01:16
Parsing of 3619 .bb files complete (3313 cached, 306 parsed). 8084 targets, 1700 skipped, 20 masked, 0 errors.
WARNING: No bb files matched BBFILE_PATTERN_local-layer '^/home/mohammad/repos/build-enviroment/meta-local/'
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'lib32-gstreamer1.0-plugins-ugly-amrnb' (but virtual:multilib:lib32:/home/mohammad/repos/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'lib32-gstreamer1.0-plugins-ugly-amrnb' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-gstreamer1.0-plugins-ugly-amrnb']
ERROR: Required build target 'lib32-enigma2' has no buildable providers.
Missing or unbuildable dependency chain was: ['lib32-enigma2', 'lib32-gstreamer1.0-plugins-ugly-amrnb']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
```
