### ISSUE TITLE
Builderror Kodi on Debian 9.5 on 64Bit Machine

### ISSUE THREAD

**Issue by schleichdi2** [oe-alliance/build-enviroment#26]
Kodi is not buildable in oenextp3 with error no egl libs found. virtual_egl is in sysroot-providers but config.log says 
'Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found'
[config.log](https://github.com/oe-alliance/build-enviroment/files/2317699/config.log)
[log.do_configure.txt](https://github.com/oe-alliance/build-enviroment/files/2317705/log.do_configure.txt)

**Comment by arn354** [comment]
nextp3 is development and far away from release... we do not build every box yet.
simply don't build it or wait untill specific boxes are built and fixed from others.
Or even better - try to fix and provide a pull-request :)

**Comment by atvcaptain** [comment]
openembedded stop support kodi 17.6

we must readd the version
