### ISSUE TITLE
when make image sf4008 box,it failed

### ISSUE THREAD

**Issue by opfans** [oe-alliance/build-enviroment#28]
openatvbuilder@jinhua-X555YI:~/openatv/build-enviroment$ MACHINE=sf4008 DISTRO=openatv DISTRO_TYPE=release make image
check internet connection: Online     
Loading cache: 100% |###########################################################################################################| Time: 0:00:02
Loaded 4961 entries from dependency cache.
WARNING: No bb files matched BBFILE_PATTERN_local-layer '^/home/openatvbuilder/openatv/build-enviroment/meta-local/'
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.40.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "sf4008"
DISTRO               = "openatv"
DISTRO_VERSION       = "6.3"
TUNE_FEATURES        = "arm armv7ve vfp neon vfpv4 callconvention-hard cortexa15"
TARGET_FPU           = "hard"
meta                 = "HEAD:bb06900a1f29fdd4066f6d7e7a961d230c2e9438"
meta-oe              
meta-multimedia      
meta-networking      
meta-filesystems     
meta-python          
meta-webserver       = "HEAD:15141ab55be96e7255fad4a03fca69cfb2ffd3d7"
meta-oe              = "HEAD:00354ca659cffbd01e59f325eb4e9e30e90f441e"
meta-qt5             = "HEAD:ad8b227a8b6fca1f0b3e07a9453f2105dcc3968b"
meta-airdigital      
meta-azbox           
meta-ax              
meta-blackbox        
meta-ceryon          
meta-clap            
meta-cube            
meta-dags            
meta-dinobot         
meta-dream           
meta-ebox            
meta-edision         
meta-entwopia        
meta-formuler        
meta-fulan           
meta-gfutures        
meta-gigablue        
meta-ini             
meta-ixuss           
meta-linkdroid       
meta-broadmedia      
meta-odin            
meta-odroid          
meta-octagon         
meta-protek          
meta-skylake         
meta-tiviar          
meta-tripledot       
meta-uclan           
meta-ultramini       
meta-vuplus          
meta-wetek           
meta-xp              
meta-xtrend          
meta-xcore           = "HEAD:00354ca659cffbd01e59f325eb4e9e30e90f441e"
meta-local           = "<unknown>:<unknown>"

Initialising tasks: 100% |#######################################| Time: 0:01:59
Sstate summary: Wanted 4857 Found 0 Missed 4857 Current 165 (0% match, 3% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: rpm-native-1_4.14.2-r0 do_unpack: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-gYUUndm2Rq"; export SSH_AUTH_SOCK="/run/user/1001/keyring/ssh"; export PATH="/home/openatvbuilder/openatv/build-enviroment/openembedded-core/scripts/native-intercept:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/recipe-sysroot-native/usr/bin/python3-native:/home/openatvbuilder/openatv/build-enviroment/openembedded-core/scripts:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/recipe-sysroot-native/usr/bin/x86_64-linux:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/recipe-sysroot-native/usr/bin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/recipe-sysroot-native/usr/sbin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/recipe-sysroot-native/usr/bin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/recipe-sysroot-native/sbin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/recipe-sysroot-native/bin:/home/openatvbuilder/openatv/build-enviroment/bitbake/bin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/hosttools"; export HOME="/home/openatvbuilder"; git -c core.fsyncobjectfiles=0 clone -s -n /home/openatvbuilder/openatv/build-enviroment/sources/git2/github.com.rpm-software-management.rpm/ /home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/git/ failed with exit code 128, output:
fatal: repository '/home/openatvbuilder/openatv/build-enviroment/sources/git2/github.com.rpm-software-management.rpm/' does not exist

ERROR: rpm-native-1_4.14.2-r0 do_unpack: Function failed: base_do_unpack
ERROR: Logfile of failure stored in: /home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/rpm-native/1_4.14.2-r0/temp/log.do_unpack.3361
ERROR: Task (virtual:native:/home/openatvbuilder/openatv/build-enviroment/openembedded-core/meta/recipes-devtools/rpm/rpm_4.14.2.bb:do_unpack) failed with exit code '1'
NOTE: Tasks Summary: Attempted 931 tasks of which 867 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  virtual:native:/home/openatvbuilder/openatv/build-enviroment/openembedded-core/meta/recipes-devtools/rpm/rpm_4.14.2.bb:do_unpack
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:914: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by atvcaptain** [comment]
you have read infos from here

https://github.com/openatv/enigma2/blob/6.3/README.md

**Comment by opfans** [comment]
> you have read infos from here
> 
> https://github.com/openatv/enigma2/blob/6.3/README.md

thank you ,i try it again
