### ISSUE TITLE
qtlocation and sensors not buildable in debian 9 strech

### ISSUE THREAD

**Issue by schleichdi2** [oe-alliance/build-enviroment#29]
Hello, in debian 9 strech qtlocation and qtsensors are not buildable. I get a segmentation_fault in both packages. I do not know if it's due to missing packages in Debian or copiler. Can you help it would be really great Box is gbue4k  Thank you

"Makefile:542: recipe for target 'sensorproxy_interface.h' failed
make[4]: *** [sensorproxy_interface.h] Segmentation fault
make[4]: *** Waiting for unfinished jobs....
Makefile:570: recipe for target 'properties_interface.h' failed
make[4]: *** [properties_interface.h] Segmentation fault
Makefile:556: recipe for target 'compass_interface.h' failed
make[4]: *** [compass_interface.h] Segmentation fault"

**Comment by atvcaptain** [comment]
we support only ubunto 16_04 LTS at the moment sorry

**Comment by schleichdi2** [comment]
ok thanks no problem
