### ISSUE TITLE
Missing Proc::ProcessTable

### ISSUE THREAD

**Issue by AxelNennker** [oe-alliance/build-enviroment#31]
Hi,

I cloned the openatv fork https://github.com/openatv/build-enviroment and followed the instructions in the README.md which includes cloning 
`git clone git://github.com/oe-alliance/build-enviroment.git -b 4.0`

Building the image for vusolose only worked after installing Proc::ProcessTable
` sudo cpanm Proc::ProcessTable`

The system used for building is Ubuntu 16.04. Searching for ProcessTable in this repo does not yield any result, so I guess the dependency on ProcessTable is in one of the many other packages used by oe-alliance. 

If you want me to upload a build log please tell me.

Axel

**Comment by arn354** [comment]
Please use branch 4.2 or 4.3
4.0 is eol - we should update readme.
Readme in openatv repository is uptodate

**Comment by AxelNennker** [comment]
What do you mean openatv's readme being uptodate? That line `git clone git://github.com/oe-alliance/build-enviroment.git -b 4.0` is from the current [openatv readme](https://github.com/openatv/build-enviroment/blob/4.0/README.md).
Thanks for clarifying.
