### ISSUE TITLE
meta-go

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/build-enviroment#32]
is there any reason why we still hold this layer in gitmodules?

**Comment by Schimmelreiter** [comment]
rclone needs it.

**Comment by nickersk** [comment]
its not in generated bblayers.conf so is it being parsed by bitbake? imho oe-core version is being used.

**Comment by nickersk** [comment]
i removed it from both nextp3 branches and i'm pretty sure it can be removed from 4.x branches too. what's your opinion?

**Comment by Schimmelreiter** [comment]
As long as rclone builds, it's ok.
