### ISSUE TITLE
build feed ?

### ISSUE THREAD

**Issue by Ormiwhite** [oe-alliance/build-enviroment#35]
hi, 

1-  I just build image openhdf , and it's work well,  now i need to know how i can build feed at local, as this image support dreambox , but the team don't build image for my box.

build image  : MACHINE=dm500hd DISTRO=openhdf DISTRO_TYPE=release make image
build feed : make: *** No rule to make target 'feed'. Stop. 
 
2- Also if some one can show me how i can install kernel-module-block2mtd , should enable something with defconfig ? i need to add something else ?

thanx.

![openhdf](https://user-images.githubusercontent.com/52411089/62515884-79e21c00-b81b-11e9-9199-0803348245e1.jpg)

**Comment by nickersk** [comment]
feeds are in tmp/deploy/ipk dir. block2mtd is enabled in defconfig.

**Comment by Ormiwhite** [comment]
thanks
