### ISSUE TITLE
4.4

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/build-enviroment#36]
@atvcaptain what is desired OE-core version for 4.4? warrior or zeus? thx

**Comment by atvcaptain** [comment]
at the moment same as nextp3

**Comment by nickersk** [comment]
so may i update 4.4 OE-core same way like i do with nextp3 branches (master-next)?

**Comment by atvcaptain** [comment]
4.4 i have start remove dead meta and boxes not working any more
and remove test sample we never have support or never on sales
i think we can remove more old boxes with less flash new images not fit or boxes to slow

**Comment by atvcaptain** [comment]
yes netxp3 you can use for master-next for play for feature updates

i start now build new beta image i have now free server ressources

**Comment by nickersk** [comment]
ok, so i will update only np3 branches to master-next. you'll update 4.4 when you wish. did i undertood?
oe-alliance-core merges from 4.3 are ok ? 4.3->4.4->np3->np3-ssl111 ?

**Comment by nickersk** [comment]
oe-alliance-core merges from 4.3 are ok ?

**Comment by atvcaptain** [comment]
you can update 4.4 so long we are on beta test too np, oe-core updates not include all for next stabel release , but not so fast or i have never a ready image :)
merge from 4.3 ok the old metas i have remove we have long time no updates, i think de dont have a merge issue

**Comment by atvcaptain** [comment]
oe-alliance-core merges from 4.3 are ok ? 4.3->4.4->np3->np3-ssl111 ?

yes

**Comment by nickersk** [comment]
thx
