### ISSUE TITLE
Adding meta

### ISSUE THREAD

**Issue by Power535** [oe-alliance/build-enviroment#37]
I have kernel src and bchip all modules including headers
Is anybody can help add to new meta ?
I will sent all files
Thank you

**Comment by atvcaptain** [comment]
meta for model ? have you more infos, link and more

**Comment by Power535** [comment]
meta-model no
I sent nickersk 
info and all files kernel include plat modules 
I try run fews years bchip 7231 , no result
Need help configure bchip modules
Do not know how here sent files
Possible here sent message in pm ?

**Comment by nickersk** [comment]
pls, send them to @atvcaptain too

**Comment by Power535** [comment]
This not email
Please email , then delete email from message

**Comment by atvcaptain** [comment]
e2 not working with native nexus drivers, rework for e2 is a very big work and for a 9 year old chip , you find no guys only you have the know for porting all

**Comment by Power535** [comment]
What not native name drivers for receivers ?

**Comment by Power535** [comment]
What name drivers for receivers ?

**Comment by Power535** [comment]
Only help with hdmi out
configure modules

**Comment by nickersk** [comment]
i didnt find any way, we can help you with this, sorry :(
