### ISSUE TITLE
Enigmalight 4.3 branch

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/build-enviroment#38]
There is a problem with Enigmalight on 4.3 branch. It does not work. If I use the binary from 4.2 branch on image using a 4.3 image, it works. can anybody assist with finding out what has changed in the build process.

Bitbake file is here
https://github.com/oe-alliance/oe-alliance-core/blob/4.3/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-extensions-enigmalight.bb

Dimitrij has said he is not doing anything with this plugin
https://forums.openpli.org/topic/49262-enigmalight-support-arm-model/page-2#entry1117928   

I have there for forked project here so taht we can make any required changes.
https://github.com/AbuBaniaz/enigmalight

There are 6 files which have minor differences in the name as well as content. I'd like to delete the ones that are not used.  How do I find out which ones are used in the build process?

```
\build\src\Include\Config.h
\build\src\Include\Config.h.in
\build\src\Include\Device\DeviceLightPack.h

\build\src\Include\config.h
\build\src\Include\config.h.in
\build\src\Include\Device\deviceLightPack.h 
```

Thanks in advance

**Comment by nickersk** [comment]
any logs ?

**Comment by AbuBaniaz** [comment]
The log is from @huevos
 
[log.do_compile.12446.txt](https://github.com/oe-alliance/build-enviroment/files/4183710/log.do_compile.12446.txt)

**Comment by nickersk** [comment]
nothing unusual there ... have we got any log from stb? or what is the behavior when running on stb?

**Comment by AbuBaniaz** [comment]
I'll try and get tomorrow or after I get back about midnight
Can you advise which files are used to build the binary files? elighttalk and enigmalight which end up in /usr/bin

**Comment by AbuBaniaz** [comment]
The behaviour is that it appears to work but doesn't. Nothing evident in logs from another user. I'll get etc my own.

There is a missing directory which has to be added manually too. But that applies to both branches. home/elight-addons.

**Comment by RobvanderDoes** [comment]
Correct: that directory has and had to be added manually.

Tested on VU-Ult 4k under 5.3.016.006 using enigma2-plugin-extensions-enigmalight_0.4-rc1_all.ipk and the two binaries (elighttalk & enigmalight) from the 5.2-branch.

Result (so far only done a quick test) seems to be the same behaviour as under 5.3 using the plugin from the feeds.

So there is a solution......

**Comment by nickersk** [comment]
according to build/src/Makefile :
enigmalight_SOURCES = \
	Main.cpp \
	MainLoop.cpp \
	FlagManager.cpp \
	Configuration.cpp \
	Util/Condition.cpp \
	Util/Log.cpp \
	Util/Misc.cpp \
	Util/Mutex.cpp \
	Util/Thread.cpp \
	Util/Timer.cpp \
	Util/Bitmap.cpp \
	Util/SerialPort.cpp \
	Util/TimeUtils.cpp \
	Util/TcpSocket.cpp \
	Util/MessageQueue.cpp \
	Util/SignalTimer.cpp \
	Util/Daemonize.cpp \
	Util/Modp_Numtoa.c \
	Util/ColorTransform.cpp \
	Util/BlackbarDetection.cpp \
	GuiServer/GuiServer.cpp \
	StbDetection/StbDetection.cpp \
	Grabber/Grabber.cpp \
	Grabber/FrameGrabber.cpp \
	Lights/EnigmaLightOptions.cpp \
	Lights/Light.cpp \
	Lights/Color.cpp \
	Effects/Effects.cpp \
	Effects/Static.cpp \
	Effects/Moodlamp.cpp \
	Effects/Rainbow.cpp \
	Effects/RGBTest.cpp \
	Device/Device.cpp \
	Device/DevicePopen.cpp \
	Device/DeviceRs232.cpp \
	Device/DeviceLTBL.cpp \
	Device/DeviceDioder.cpp \
	Device/DeviceAmbioder.cpp \
	Device/DeviceIbelight.cpp \
	Device/DeviceLightpack.cpp

elighttalk_SOURCES = \
	ElightTalk/Main.cpp \
	Util/Misc.cpp

**Comment by nickersk** [comment]
output of cat /proc/stb/info/chipset and cat /proc/stb/info/model is ? to let us see it the stb is correctly detected in src/StbDetection/StbDetection.cpp

**Comment by AbuBaniaz** [comment]
Just for information, the issue on ATV forum is here:
https://www.opena.tv/plugins/45470-openatv-6-3-enigmalight-vu-solo-se-v2.html

Lots of boxes show wrong box name as a workaround for some old cams, this is a driver issue and explains why my box is shown as a DM8000. Chipset is correct (7362) 

TM Nano SE M2 on 4.3 branch
```
Welcome to OpenViX for tmnanosem2
openvix 5.3 tmnanosem2

tmnanosem2 login: root
root@tmnanosem2:~# cat /proc/stb/info/chipset
7362
root@tmnanosem2:~# cat /proc/stb/info/model
dm8000
root@tmnanosem2:~#
```

On 4.2 branch, still the same
```

Welcome to OpenViX for tmnanosem2
openvix 5.2 tmnanosem2

tmnanosem2 login: root
root@tmnanosem2:~# cat /proc/stb/info/chipset
7362
root@tmnanosem2:~# cat /proc/stb/info/model
dm8000
root@tmnanosem2:~#
```

I attach E2 debug logs as well as the logs created in /home/elight-addons/.enigmalight 

I flashed 4.3 image and installed from the plugin server via Vix plugin restore. I added the missing folder. Lights flash momentarily and it does not work
I then transferred the binaries from 4.2 branch and used on same image, rebotted. It worked.

I flashed 4.2 image and installed from the plugin server via Vix plugin restore. I added the missing folder. It started without a problem


[enigmalight_logs.zip](https://github.com/oe-alliance/build-enviroment/files/4189534/enigmalight_logs.zip)

**Comment by nickersk** [comment]
i unpacked ipk in orig. repo and its contents differs by what is built from bb recipe. maybe would be worth to adjust recipe to create dir structure with files like in original ipk. what do you think ? can you please send me working ipk somewhere? thx

**Comment by nickersk** [comment]
ok, made some changes locally. can you try bitbake with recipe from https://gthub.com/nickersk/test ? just replace original bb with bb from test git.

**Comment by nickersk** [comment]
ok, made some changes locally. can you try bitbake with recipe from https://github.com/nickersk/enigma2-plugin-extensions-enigmalight ? just replace original bb with bb from test git. should be ready now.

**Comment by AbuBaniaz** [comment]
Sorry about delayed response, you can get an ipk from 4.2 branch here
```
http://www.openvix.co.uk/feeds/openvix/release/5.2/dags7362/mips32el/enigma2-plugin-extensions-enigmalight_0.4+git54+b3d012c-r0_mips32el.ipk
```
However, it is missing the  elight-addons folder in home directory

**Comment by AbuBaniaz** [comment]
Thanks.

I am using a different receiver as that is the build environment i had setup. Installation stalls on this. This was a new flash with nothing restored. 

```
root@tmnano3t:~# opkg install enigma2-plugin-extensions-enigmalight
Installing curl (7.62.0) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7356/mips32el/curl_7.62.0-r0_mips32el.ipk.
Installing kernel-module-cdc-acm-3.9.7 (3.9.7) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7356/dags7356/kernel-module-cdc-acm-3.9.7_3.9.7-.1_dags7356.ipk.
Installing kernel-module-ch341-3.9.7 (3.9.7) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7356/dags7356/kernel-module-ch341-3.9.7_3.9.7-.1_dags7356.ipk.
Installing enigma2-plugin-extensions-enigmalight (1.0+git5+90d2a85) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7356/mips32el/enigma2-plugin-extensions-enigmalight_1.0+git5+90d2a85-r2_mips32el.ipk.

Check if enigmalight is running...

enigmalight: not running
Checking for /etc/enigmalight.conf...
File /etc/enigmalight.conf does not exist in /etc/
Create backups from profiles...
no profiles found..
Checking for an older version of EnigmaLight...
EnigmaLight was not found in the system
Proceeding to installation...
Configuring kernel-module-ch341-3.9.7.
Configuring curl.
Configuring kernel-module-cdc-acm-3.9.7.
Configuring enigma2-plugin-extensions-enigmalight.
mkdir: can't create directory '/usr/lib/enigma2/python/Plugins/Extensions/EnigmaLight/profiles/': File exists
Collected errors:
 * pkg_run_script: package "enigma2-plugin-extensions-enigmalight" postinst script returned status 1.
 * opkg_configure: enigma2-plugin-extensions-enigmalight.postinst returned 1.
root@tmnano3t:~# 
```

For information, 
build process had these warnings
```
Initialising tasks: 100% |##################################################################################################################################| Time: 0:00:00
Sstate summary: Wanted 5 Found 0 Missed 5 Current 0 (0% match, 0% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: enigma2-plugin-extensions-enigmalight-1.0+gitAUTOINC+90d2a85934-r2 do_package_qa: QA Issue: enigma2-plugin-extensions-enigmalight rdepends on glibc, but it isn't a build dependency, missing glibc in DEPENDS or PACKAGECONFIG? [build-deps]
WARNING: enigma2-plugin-extensions-enigmalight-1.0+gitAUTOINC+90d2a85934-r2 do_package_qa: QA Issue: enigma2-plugin-extensions-enigmalight rdepends on libgcc, but it isn't a build dependency, missing libgcc in DEPENDS or PACKAGECONFIG? [build-deps]
WARNING: enigma2-plugin-extensions-enigmalight-1.0+gitAUTOINC+90d2a85934-r2 do_package_qa: QA Issue: enigma2-plugin-extensions-enigmalight rdepends on libstdc++, but it isn't a build dependency, missing gcc-runtime in DEPENDS or PACKAGECONFIG? [build-deps]
WARNING: enigma2-plugin-extensions-enigmalight-1.0+gitAUTOINC+90d2a85934-r2 do_package_qa: QA Issue: enigma2-plugin-extensions-enigmalight rdepends on libusb1, but it isn't a build dependency, missing libusb1 in DEPENDS or PACKAGECONFIG? [build-deps]
NOTE: Tasks Summary: Attempted 16 tasks of which 1 didn't need to be rerun and all succeeded.
```
Should it not be `libusb` instead of `libusb1`

**Comment by nickersk** [comment]
in 4.3 branch there is libusb1 recipe, will need to tweak postinst script, as /usr/lib/enigma2/python/Plugins/Extensions/EnigmaLight/profiles/ exists ... still i wonder how it could exist after clean flash :-)

**Comment by AbuBaniaz** [comment]
Here is the ipk that was built if it helps

[enigma2-plugin-extensions-enigmalight_1.0+git5+90d2a85-r2_mips32el.zip](https://github.com/oe-alliance/build-enviroment/files/4194837/enigma2-plugin-extensions-enigmalight_1.0%2Bgit5%2B90d2a85-r2_mips32el.zip)

**Comment by AbuBaniaz** [comment]
Here is the ipk that was built if it helps

[enigma2-plugin-extensions-enigmalight_1.0+git5+90d2a85-r2_mips32el.zip](https://github.com/oe-alliance/build-enviroment/files/4194841/enigma2-plugin-extensions-enigmalight_1.0%2Bgit5%2B90d2a85-r2_mips32el.zip)

**Comment by nickersk** [comment]
thx, can you give it another try? ..just updated recipe

**Comment by AbuBaniaz** [comment]
I'm back on tmannosem2. 

1. No warnings during build process

2. Installation still has an issue
```
root@tmnanosem2:~# opkg install enigma2-plugin-extensions-enigmalight
Installing curl (7.62.0) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/mips32el/curl_7.62.0-r0_mips32el.ipk.
Installing kernel-module-cdc-acm-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-cdc-acm-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-usbserial-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-usbserial-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-ch341-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-ch341-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-ftdi-sio-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-ftdi-sio-4.2.1_4.2.1-.3_dags7362.ipk.
Installing enigma2-plugin-extensions-enigmalight (1.0+git6+b4745b3) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/mips32el/enigma2-plugin-extensions-enigmalight_1.0+git6+b4745b3-r3_mips32el.ipk.

Check if enigmalight is running...

enigmalight: not running
Checking for /etc/enigmalight.conf...
File /etc/enigmalight.conf does not exist in /etc/
Create backups from profiles...
no profiles found..
Checking for an older version of EnigmaLight...
EnigmaLight was not found in the system
Proceeding to installation...
Configuring kernel-module-usbserial-4.2.1.
Configuring kernel-module-cdc-acm-4.2.1.
Configuring curl.
Configuring kernel-module-ch341-4.2.1.
Configuring kernel-module-ftdi-sio-4.2.1.
Configuring enigma2-plugin-extensions-enigmalight.
- Added profiles...
>>> Configuring EnigmaLight...
- Reload udev rules...
Collected errors:
 * pkg_run_script: package "enigma2-plugin-extensions-enigmalight" postinst script returned status 127.
 * opkg_configure: enigma2-plugin-extensions-enigmalight.postinst returned 127.
root@tmnanosem2:~# 
```

**Comment by AbuBaniaz** [comment]
Can we try removing these lines?
```
echo "- Reload udev rules..."
udevadm control --reload-rules 1>/dev/null 2>/dev/null

echo "- Remove installation files..."
rm -rf /DEBIAN 1>/dev/null
```

**Comment by nickersk** [comment]
eudev breaks hdd mount, so yes will remove those lines... done

**Comment by AbuBaniaz** [comment]
Builds and installs without errors. Many thanks.
```
root@tmnanosem2:~# opkg install enigma2-plugin-extensions-enigmalight
Installing curl (7.62.0) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/mips32el/curl_7.62.0-r0_mips32el.ipk.
Installing kernel-module-cdc-acm-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-cdc-acm-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-usbserial-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-usbserial-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-ch341-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-ch341-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-ftdi-sio-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-ftdi-sio-4.2.1_4.2.1-.3_dags7362.ipk.
Installing enigma2-plugin-extensions-enigmalight (1.0+git7+4e0936f) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/mips32el/enigma2-plugin-extensions-enigmalight_1.0+git7+4e0936f-r4_mips32el.ipk.

Check if enigmalight is running...

enigmalight: not running
Checking for /etc/enigmalight.conf...
File /etc/enigmalight.conf does not exist in /etc/
Create backups from profiles...
no profiles found..
Checking for an older version of EnigmaLight...
EnigmaLight was not found in the system
Proceeding to installation...
Configuring kernel-module-usbserial-4.2.1.
Configuring kernel-module-cdc-acm-4.2.1.
Configuring curl.
Configuring kernel-module-ch341-4.2.1.
Configuring kernel-module-ftdi-sio-4.2.1.
Configuring enigma2-plugin-extensions-enigmalight.
- Added profiles...
>>> Configuring EnigmaLight...


#####################  EnigmaLight installed... ####################

                    You can now use the Plugin.
            Please RESTART Enigma2 to activate the GUI.
           don't forget to create a configuration file :)


         >>> For samplefiles look in /home/elight-addons/ <<<

####################################################################

```
We need to tweak the message about location of the sample config files.
```
>>> For samplefiles look in /home/elight-addons/ <<<
```

Configuration does not give the error about missing directory. Thanks again.

My unit has broken, it does not flash at start, so sure it is hardware issue. I need to investigate and fix. I'm expecting a new arduino so will be able to test when it arrives. 

Many thanks once again

Mipsel ipk attached for anybody wanting to test.

[enigma2-plugin-extensions-enigmalight_1.0+git7+4e0936f-r4_mips32el.zip](https://github.com/oe-alliance/build-enviroment/files/4195945/enigma2-plugin-extensions-enigmalight_1.0%2Bgit7%2B4e0936f-r4_mips32el.zip)

**Comment by nickersk** [comment]
ok, will do install msg tweak as you suggested. thx

**Comment by AbuBaniaz** [comment]
I built this after your commits about 8 hours ago

Just for reference, installation process was fine. I won't be posting it again unless there is an issue
```
root@tmnanosem2:~# opkg install enigma2-plugin-drivers-usbserial
Installing kernel-module-usbserial-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-usbserial-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-belkin-sa-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-belkin-sa-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-ftdi-sio-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-ftdi-sio-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-ezusb-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-ezusb-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-keyspan-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-keyspan-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-pl2303-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-pl2303-4.2.1_4.2.1-.3_dags7362.ipk.
Installing enigma2-plugin-drivers-usbserial (1.0) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/mips32el/enigma2-plugin-drivers-usbserial_1.0-r0_mips32el.ipk.
Configuring kernel-module-ezusb-4.2.1.
Configuring kernel-module-usbserial-4.2.1.
Configuring kernel-module-ftdi-sio-4.2.1.
Configuring kernel-module-pl2303-4.2.1.
Configuring kernel-module-keyspan-4.2.1.
Configuring kernel-module-belkin-sa-4.2.1.
Configuring enigma2-plugin-drivers-usbserial.
root@tmnanosem2:~# opkg install enigma2-plugin-extensions-enigmalight
Installing curl (7.62.0) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/mips32el/curl_7.62.0-r0_mips32el.ipk.
Installing kernel-module-cdc-acm-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-cdc-acm-4.2.1_4.2.1-.3_dags7362.ipk.
Installing kernel-module-ch341-4.2.1 (4.2.1) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/dags7362/kernel-module-ch341-4.2.1_4.2.1-.3_dags7362.ipk.
Installing enigma2-plugin-extensions-enigmalight (1.0+git16+62d2c31) on root.
Downloading 192.168.0.70/feeds/openvix/abu/5.3/dags7362/mips32el/enigma2-plugin-extensions-enigmalight_1.0+git16+62d2c31-r6_mips32el.ipk.

Check if enigmalight is running...

enigmalight: not running
Checking for /etc/enigmalight.conf...
File /etc/enigmalight.conf does not exist in /etc/
Create backups from profiles...
No profiles found...
Checking for an older version of EnigmaLight...
EnigmaLight was not found in the system
Proceeding to installation...
Configuring kernel-module-cdc-acm-4.2.1.
Configuring curl.
Configuring kernel-module-ch341-4.2.1.
Configuring enigma2-plugin-extensions-enigmalight.
- Added profiles...
>>> Configuring EnigmaLight...


######################  EnigmaLight installed... ####################

                    You can now use the Plugin.
            Please RESTART Enigma2 to activate the GUI.
           don't forget to create a configuration file :)


  >>> For samplefiles look in /home/elight-addons/config_samples <<<

#####################################################################

root@tmnanosem2:~# 
```

There is still a problem with the two binary files. Starting the lights results in the lights flashing momentarily, screen says `info: [write adjust]` and status returning to not running. I attache the E2 debug log, the log from application too.

Starting from console did not show anything useful. Log location is displayed incorrectly. The log file is in /tmp/ , not `/home/elight-addons/.enigmalight/enigmalight.log`

```
tmnanosem2 login: root
root@tmnanosem2:~# enigmalight -m 0 -f -c /etc/enigmalight.conf

EnigmaLight (c) 2014 Speedy1985 and Oktay Oeztueter.
(Based on Boblight (c) 2009 by Bob Loosen)

[InitLog]                       start of log /home/elight-addons/.enigmalight/enigmalight.log
[CConfig::LoadConfigFromFile]   Opening /etc/enigmalight.conf
[CConfig::CheckConfig]          checking config lines
[CConfig::CheckConfig]          config lines valid
root@tmnanosem2:~# 
```

If I replace the binary files with those from 4.2 branch it starts without a problem. The binary files are installed with 755 properties, so taht is not an issue.

[enigmalight_gui.log.txt](https://github.com/oe-alliance/build-enviroment/files/4207746/enigmalight_gui.log.txt)

[Enigma2_debug_2020-02-15_04-17-34.log.txt](https://github.com/oe-alliance/build-enviroment/files/4207747/Enigma2_debug_2020-02-15_04-17-34.log.txt)

**Comment by AbuBaniaz** [comment]
I have a 4.2 build environment still setup. I can build the plugin from 4.2 branch environment as well and we can compare the processes if you want? Is there a way to specifcy where the compile log is written to instead of going through all the folders?

**Comment by nickersk** [comment]
you can use find . |grep enigmalight|grep log.do_compile in tmp/work dir of build. this could show you the full path to compile log. can you run with -d (debug)? enigmalight -d -m 0 -f -c /etc/enigmalight.conf

**Comment by AbuBaniaz** [comment]
With debug does not give any more information

```
root@tmnanosem2:~# enigmalight -d -m 0 -f -c /etc/enigmalight.conf

EnigmaLight (c) 2014 Speedy1985 and Oktay Oeztueter.
(Based on Boblight (c) 2009 by Bob Loosen)

[InitLog]                       start of log /home/elight-addons/.enigmalight/enigmalight.log
[CConfig::LoadConfigFromFile]   Opening /etc/enigmalight.conf
[CConfig::CheckConfig]          checking config lines
[CConfig::CheckConfig]          config lines valid
root@tmnanosem2:~# 
```
4.2 branch does not build any more because of the libbluray failure. There was a commit in 4.3 branch in June 2019 last year to fix it. I am a novice user, so don't want to risk breaking things by cherry picking it. I tried to manually replace local files, it but did not work for me. Suppose no point doing anything with that now

```
https://github.com/oe-alliance/oe-alliance-core/commit/d5193ea2ece3359ed39c62042d6d2269e85c6453
```


I built the old version of the plugin, but I cant find the log
[bitbake-cookerdaemon.log.txt](https://github.com/oe-alliance/build-enviroment/files/4208957/bitbake-cookerdaemon.log.txt)

I tried installing the debug version, that did not help. I have added some dmesg message which show a sigsev error

[enigmalight_manual_run.txt](https://github.com/oe-alliance/build-enviroment/files/4208971/enigmalight_manual_run.txt)

**Comment by nickersk** [comment]
do we have src package of working version somewhere?

**Comment by AbuBaniaz** [comment]
I thought everything was built from source. Attached are the two files from 4.2 branch. They go in /usr/bin

[Enigmalight mips binary from 4.2 branch.zip](https://github.com/oe-alliance/build-enviroment/files/4211109/Enigmalight.mips.binary.from.4.2.branch.zip)

**Comment by nickersk** [comment]
everything is built from actual sources (yours fork).  we need to compare working sources with recent sources or use gdb ...we need something like  enigma2-plugin-extensions-enigmalight-src_0.4+git54+b3d012c-r0_mips32el.ipk or find out which is the last working commit on git ...

**Comment by AbuBaniaz** [comment]
There have been no changes to the plugin's repository. It just never worked when we moved to 4.3 branch.

In the deploy directory, I only have dbg, mipsel and dev versions. I found a folder in the temp directory, I have zipped it and attach it here.

[enigma2-plugin-extensions-enigmalight_temp.zip](https://github.com/oe-alliance/build-enviroment/files/4211349/enigma2-plugin-extensions-enigmalight_temp.zip)

I am on the ATV's slack channel if it helps with instant communication.

Thanks for the time spent on this so far

**Comment by nickersk** [comment]
hi, made some changes, pls test ipk @ 4.3 branch of my fork. thx. PS. i dont know how to get to ATV's slack channel... - never used it before...

**Comment by AbuBaniaz** [comment]
I tried the updated ipk, same problem.

Running by command line with debug log shows no reason either
```
root@tmnanosem2:~# enigmalight -d -m 0 -f -c /etc/enigmalight.conf

EnigmaLight (c) 2014 Speedy1985 and Oktay Oeztueter.
(Based on Boblight (c) 2009 by Bob Loosen)

[InitLog]                       start of log /home/elight-addons/.enigmalight/enigmalight.log
[CConfig::LoadConfigFromFile]   Opening /etc/enigmalight.conf
[CConfig::CheckConfig]          checking config lines
[CConfig::CheckConfig]          config lines valid
root@tmnanosem2:~#
```

**Comment by nickersk** [comment]
do_page_fault(): sending SIGSEGV to enigmalight for invalid read access from 005cfa3c
epc = 00420f7c in enigmalight[400000+37000]
ra  = 0041bb54 in enigmalight[400000+37000]
this is our problem, right now i have no idea how to find broken code without debugging...

**Comment by nickersk** [comment]
will fork again and start from scratch, closing for now ...

**Comment by AbuBaniaz** [comment]
Just for reference:
https://github.com/nickersk/enigmalight

**Comment by RobvanderDoes** [comment]
> 
> 
> will fork again and start from scratch, closing for now ...

Thanks, but as far as I can see no further development took place. And the issue, using OE-A 4.4 is still the same.

**Comment by atvcaptain** [comment]
no one build 4.3 images any more now all on 5.0
