### ISSUE TITLE
boot from usb

### ISSUE THREAD

**Issue by Power535** [oe-alliance/build-enviroment#39]
No help ((

**Comment by nickersk** [comment]
if you want clean usb boot i think you need to change boot device in cfe if possible

**Comment by Power535** [comment]
Need change config machine for compile image for USB (not for Nand) my message earlier
How this make ?
Only then change booting in bootloader

**Comment by nickersk** [comment]
it is not possible to get to cfe on every machine ... you need to connect to stb (serial or other) console and search internet...

**Comment by Power535** [comment]
I know how to connect
Need change config (no Nand)

**Comment by nickersk** [comment]
https://en.wikipedia.org/wiki/Common_Firmware_Environment you need to change boot parameters there.

**Comment by Power535** [comment]
I know this
Need change config (no Nand) for compile not UBI

**Comment by nickersk** [comment]
study yocto FSTYPES variable.

**Comment by Power535** [comment]
Topic will be useful to those
who has defective Nand or many bad sectors in Nand

**Comment by nickersk** [comment]
if i should have many bad sectors in nand i would replace nand chip or buy new stb...usb is useful for old stbs with low mem or for multiboot images imho.

**Comment by Power535** [comment]
Nand hard to replace

**Comment by atvcaptain** [comment]
only open multiboot works but you need kernel and rootfs in nand flash
