### ISSUE TITLE
oe-alliance 2.4 and glibc 2.20, kernel < 2.6.32 are not supported

### ISSUE THREAD

**Issue by athoik** [oe-alliance/build-enviroment#4]
Hello,

I've notice that branch 2.4 has [glibc 2.20](https://github.com/openembedded/openembedded-core/tree/219e793/meta/recipes-core/glibc)

Here some info about the change: [The minimum Linux kernel version that this version of the GNU C Library can be used with is 2.6.32.](https://sourceware.org/ml/libc-alpha/2014-09/msg00088.html), [bitbake.conf: Use 2.6.32 for oldest supported kernel](http://permalink.gmane.org/gmane.comp.handhelds.openembedded.scm/80293)

meta-dream DM800 with [2.6.18](https://github.com/oe-alliance/oe-alliance-core/blob/2.3/meta-brands/meta-dream/recipes-linux/linux-dreambox_2.6.18.bb) is out.

meta-fulan has [2.6.32](https://github.com/oe-alliance/oe-alliance-core/blob/2.3/meta-brands/meta-fulan/recipes-linux/linux-fulan_2.6.32.bb), so just passes the limit.

meta-cube has [2.6.34](https://github.com/oe-alliance/oe-alliance-core/blob/2.4/meta-brands/meta-cube/recipes-linux/linux-cube_2.6.34.bb), so it's ok.

All other boxes are using 3.x kernels so no near issue with glibc.

**Comment by atvcaptain** [comment]
yes dm800 support its not possible with newer glibc so we cant merge dm800 to newer version dm800 now freeze in oe-a 2.3 , fulan and cube compile was ok, only a guy can create a patch for the old dm800 but its looks not good, its say good buy to the dm800

**Comment by AbuBaniaz** [comment]
Does this need to stay open?
