### ISSUE TITLE
Makefile option has gone away in 4.4

### ISSUE THREAD

**Issue by original-birdman** [oe-alliance/build-enviroment#40]
https://github.com/oe-alliance/build-enviroment/commit/943e01d3e5f630fffc9fc14aeba84582ccf10798 is missing from the 4.4 branch.

**Comment by AbuBaniaz** [comment]
This is there according to this

![opt arch](https://user-images.githubusercontent.com/6644489/76706415-39b31800-66df-11ea-8255-5961d158e5d5.PNG)

**Comment by AbuBaniaz** [comment]
But was removed here
https://github.com/oe-alliance/build-enviroment/commit/14eb43722a5fea46716a81de5fcef730da9cde83

Maybe @atvcaptain can add more information

**Comment by original-birdman** [comment]
Thanks. I've commented on that revert which, from the title, has reverted the wrong commit!

**Comment by AbuBaniaz** [comment]
I don't  understand what the problem was. @atvcaptain said 

>he can add local, we have remove we get many compile errors with ubunto 18_4 LTS

>see some commit before this last commit

**Comment by original-birdman** [comment]
No idea where he said this, so I can't  see what he's referring to.

It's rubbish, though. That commit only affected things if you specifically set OPT_ARCH in your environment.

And the reference to "local" doesn't help. as there is no description at all of where a local file should go, and it cannot override compilation options which are set in the Makefile.

**Comment by nickersk** [comment]
i suggest:if we want to readd this - there should be check when no opt_arch in cmd no -march should be forwarded to cmdline. there should be -march=something only when present in cmdline.can you try to script it that way pls? make image -> make image (no -march setted)
OPT_ARCH=native  make image -> -march=native make image

**Comment by original-birdman** [comment]
The way it works is:
```
make mage -> -march=native
make image OPT_ARCH=xyzzy -> -march=xyzzy
```
So unless you set OPT_ARCH you get the default. That's the whole point of the way it is done.

See the _very_ simple example in:
https://github.com/oe-alliance/build-enviroment/commit/943e01d3e5f630fffc9fc14aeba84582ccf10798#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by nickersk** [comment]
..and we want it to be make image -> nothing
make image OPT_ARCH=xyzzy -> -march=xyzzy

**Comment by original-birdman** [comment]
> ..and we want it to be make image -> nothing

Why do you want that?
And why has it not been mentioned before.
And why, in that case, don't you just remove the `-march` part from the Makefile completely?

**Comment by nickersk** [comment]
setting -march=native broke build of some packages like nfs, which took build flags inside and failed to cross compile. thats why. and setting march to native is useless on x86 archs. (thats why openembedded dont use it either) and btw there was some discussion in meta-oe-alliance not here. so you have to watch there too...

**Comment by original-birdman** [comment]
> and setting march to native is useless on x86 archs

Depends what you mean by "useless". It does have an effect. Which is why  I added OPT_ARCH, so that I could set the oldest chipset I use (I move my build disk between systems).
But removing it completely would have the same effect....

**Comment by original-birdman** [comment]
If you want to make the default empty, but allow anyone who wants to to set it you coudl use:
```
OPT_ARCH=
.....
        @echo 'BUILD_OPTIMIZATION = "$(OPT_ARCH) -O2 -pipe"' >> $@       
```
and then anyone who wants it could use `make image OPT_ARCH="-march native"`

**Comment by nickersk** [comment]
i agree in your case, but safety first :-) it took hours to find that many problems did -march set to native.

**Comment by nickersk** [comment]
no problem what you wrote above, can you prepare PR? i am busy on other things right now. thx

**Comment by original-birdman** [comment]
> And why, in that case, don't you just remove the -march part from the Makefile completely?

Or is that what you have actually done? I thought otherwise, but could be wrong...

**Comment by nickersk** [comment]
-march=native was removed...

**Comment by original-birdman** [comment]
OK. Turns out that -march _has_ been removed. Sorry, but given that the OPT_ARCH commit had been reverted I assume to had just gone back to the original.

I'm happy with it not being there at all.

Sorry to have bothered you unnecessarily.

**Comment by nickersk** [comment]
no problem, things needs to be explained. as i said sooner if you want (will want )opt_arch again create pr we will merge it.
