### ISSUE TITLE
Error building OATV 6.4 Win10 WSL

### ISSUE THREAD

**Issue by jeepcook** [oe-alliance/build-enviroment#47]
Hello,

For few days, an error occur when compiling OATV 6.4 on Winbdows 10 WSL Ubuntu 20.04. The error is at the end of the compilation (do_rootfs). Error chown: invalid user: ‘root:root’, the building user is openatvbuilder64.

Here is the log:

NOTE: Running intercept scripts:
NOTE: If an image is being built, the postinstalls for the following packages will be postponed for first boot: ntpdate
NOTE: > Executing update_gio_module_cache intercept ...
NOTE: Exit code 1. Output:
+ '[' True = False -a qemuwrapper-cross '!=' nativesdk-qemuwrapper-cross ']'
+ qemu-arm -r 3.2.0 -E LD_LIBRARY_PATH=/home/openatvbuilder64/openatv/build-enviroment/builds/openatv/release/hd51/tmp/work/hd51-oe-linux-gnueabi/openatv-image/6.4-20210522/rootfs/linuxrootfs1/usr/lib:/home/openatvbuilder64/openatv/build-enviroment/builds/openatv/release/hd51/tmp/work/hd51-oe-linux-gnueabi/openatv-image/6.4-20210522/rootfs/linuxrootfs1/lib -L /home/openatvbuilder64/openatv/build-enviroment/builds/openatv/release/hd51/tmp/work/hd51-oe-linux-gnueabi/openatv-image/6.4-20210522/rootfs/linuxrootfs1 /home/openatvbuilder64/openatv/build-enviroment/builds/openatv/release/hd51/tmp/work/hd51-oe-linux-gnueabi/openatv-image/6.4-20210522/rootfs/linuxrootfs1/usr/libexec/gio-querymodules /home/openatvbuilder64/openatv/build-enviroment/builds/openatv/release/hd51/tmp/work/hd51-oe-linux-gnueabi/openatv-image/6.4-20210522/rootfs/linuxrootfs1/usr/lib/gio/modules/
chown: invalid user: ‘root:root’

ERROR: The postinstall intercept hook 'update_gio_module_cache' failed, details in /home/openatvbuilder64/openatv/build-enviroment/builds/openatv/release/hd51/tmp/work/hd51-oe-linux-gnueabi/openatv-image/6.4-20210522/temp/log.do_rootfs
DEBUG: Python function do_rootfs finished

**Comment by jeepcook** [comment]
Hello,

Find a fix by removing chown root:root command in all scripts under ~/openatv/build-enviroment/openembedded-core/scripts/postinst-intercepts
I think it's a choice for openembedded but useless for enigma2 because everything has root attributes. So the build process has to mod this script.
Is my explanation ok for you ?

Thanks

**Comment by jeepcook** [comment]
hello,
no dev want to fix this issue ?
thanks

**Comment by nickersk** [comment]
hi, you can request a bug fix at https://bugzilla.yoctoproject.org  we use openembedded only as git submodules...

**Comment by nickersk** [comment]
closing due to no feedback for several months. reopen if needed.
