### ISSUE TITLE
image is not compiling

### ISSUE THREAD

**Issue by justason** [oe-alliance/build-enviroment#7]
ERROR: Nothing PROVIDES 'libxau' (but /home/developer/build-enviroment/meta-oe-alliance/meta-oe/recipes-extended/libungif/libungif_4.1.4.bb DEPENDS on or otherwise requires it)

**Comment by henrylicious** [comment]
https://github.com/oe-alliance/oe-alliance-core/commit/f8a494c9731379dd345078d04e70886cadca8949
problem is fixed now
