### ISSUE TITLE
fix the checksums for python-circuits_2.1.0.bb recipe

### ISSUE THREAD

**Issue by justason** [oe-alliance/build-enviroment#8]
WARNING: Checksum failure encountered with download of https://bitbucket.org/prologic/circuits/get/42e62ab9f8dd.zip - will attempt other sources if available
WARNING: Renaming /home/developer/build-enviroment/sources/42e62ab9f8dd.zip to /home/developer/build-enviroment/sources/42e62ab9f8dd.zip_bad-checksum_35b09153c13eb5151f219b9857328c96
ERROR: Fetcher failure for URL: 'https://bitbucket.org/prologic/circuits/get/42e62ab9f8dd.zip'. Checksum mismatch!
File: '/home/developer/build-enviroment/sources/42e62ab9f8dd.zip' has md5 checksum 35b09153c13eb5151f219b9857328c96 when 918a4afe4cd30183695359da7bd6d819 was expected
File: '/home/developer/build-enviroment/sources/42e62ab9f8dd.zip' has sha256 checksum bddf798d44cc3b149c187eea1df6c78df90de75a873f6401aadc45c2d5ecedea when c59e5bc43e52475035c0de34a26ab413b29108e527a21653551cdb251ac926b0 was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "35b09153c13eb5151f219b9857328c96"
SRC_URI[sha256sum] = "bddf798d44cc3b149c187eea1df6c78df90de75a873f6401aadc45c2d5ecedea"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

ERROR: Function failed: Fetcher failure for URL: 'https://bitbucket.org/prologic/circuits/get/42e62ab9f8dd.zip'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/developer/build-enviroment/builds/openatv/release/wetekplay/tmp/work/cortexa9hf-vfp-neon-oe-linux-gnueabi/python-circuits/2.1.0-r3/temp/log.do_fetch.14832
ERROR: Task 5080 (/home/developer/build-enviroment/meta-oe-alliance/meta-oe/recipes-devtools/python/python-circuits_2.1.0.bb, do_fetch) failed with exit code '1'

**Comment by atvcaptain** [comment]
allready fixed
