### ISSUE TITLE
'enviroment' should be spelled environment 

### ISSUE THREAD

**Issue by wwortel** [oe-alliance/build-enviroment#9]
The title is self explanatory.

**Comment by arn354** [comment]
we know for a long time - it seems a "simple" change but results in any team having to start a new build.

**Comment by Schimmelreiter** [comment]
That's not really an issue.

The proper spelling for referer is referrer, but the wrong writing "referer" made it into RFC2068 and nobody cares.
The only change to RFC2068 was to add a "sic!" behind mentionings of "referer" to indicate that the wrong spelling is technically correct.

**Comment by wwortel** [comment]
@Schimmelreiter 
Spelling is part of the technology of language and the chosen spelling is technically not correct. As a side effect it gives a negative connotation to what seems an impressive collection of work. Like a dirty flag on top of an immaculate building.

After having cloned the repository I have renamed it before 'make'. That seems to work to not having to look at a term that is an odd english-french mix the way it is spelled.
